### ISSUE TITLE
Use linchpin hooks if possible

### ISSUE THREAD

**Issue by robled** [RedHatQE/cinch#127]
Now that linchpin supports postup and predestroy hooks as of the 1.0.0 release, we should try to use them.  Here is an example of what hooks would look like in the linchpin PinFile:

```
    cinch:
      topology: cinch.yml
      layout: cinch.yml
      hooks:
        postup:
          - name: cinchup
            type: shell
            context: false
            actions:
              - echo Running postup
              - ansible-playbook -i inventories/cinch.inventory /paht/to/cinch/cinch/site.yml
        predestroy:
          - name: cinchdestroy
            type: shell
            context: false
            actions:
              - echo Running predestroy
              - ansible-playbook -i inventories/cinch.inventory /path/to/cinch/cinch/teardown.yml
```
