### ISSUE TITLE
Unable to log into Jenkins admin account on deployed Jenkins

### ISSUE THREAD

**Issue by ddelabru** [RedHatQE/cinch#233]
I'm working on an automated process to deploy a new Jenkins master, run a few tests on it, and tear it down once the tests are complete. (There's a reason for this.) I've been using cinch successfully so far, but I've noticed that if I enable the Jenkins security settings with something like the following in my `group_vars/all` file, I will not be able to log into the jenkins-admin account on the web interface with my_super_secure_password as the password.

```
jenkins_security_enabled: true
jenkins_admin:
  nickname: jenkins-admin
  email: root@localhost
  password: my_super_secure_password
jenkins_kerberos_anonymous_access: false
```

Ultimately, it looks like I can still use Ansible to access the Jenkins master with the right SSH key, and I may be able to programmatically get an API token for what I need, but I was surprised that the deployed Jenkins behaved this way.
